#
# Общие настройки AeroSpace
#
start-at-login = false                                                 # Запуск AeroSpace при входе в систему
enable-normalization-flatten-containers = true                         # Нормализация контейнеров для предсказуемого поведения
enable-normalization-opposite-orientation-for-nested-containers = true # Автоматическая смена ориентации для вложенных контейнеров

accordion-padding = 300                     # Размер отступов в режиме аккордеона. Для одного окна на экране это не так критично.
default-root-container-layout = 'tiles'     # По умолчанию используем тайловый режим
default-root-container-orientation = 'auto' # Автоматическая ориентация для контейнеров

# Перемещение мыши при смене фокуса монитора
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Отключение автоматического скрытия приложений (Cmd+H)
automatically-unhide-macos-hidden-apps = false

#
# Назначение рабочих столов на мониторы
#
# Это помогает AeroSpace "знать", какой монитор считать "main" и куда отправлять рабочие столы.
# Номера мониторов отсчитываются слева направо: 1, 2, 3...
# 'main' указывает на основной монитор macOS.
# Если у вас два монитора, а '2' - это второй монитор, тогда 'main' может быть 1 или 2.
# AeroSpace автоматически создает рабочий стол, если его нет.
# [workspace-to-monitor-force-assignment]
# 1 = 1      # Рабочий стол 1 на мониторе 1 (первом слева)
# 2 = 'main' # Рабочий стол 2 на основном мониторе (который вы установили в System Settings)
# 'T', 'Z', 'O' - это именованные рабочие столы, они не обязательно привязываются к мониторам,
# если вы просто хотите, чтобы они существовали и были доступны.
# Если вы хотите, чтобы они ВСЕГДА открывались на конкретном мониторе, укажите его номер здесь.
# Например, если 'T' всегда на мониторе 2: T = 2

#
# Правила для плавающих окон
#
# Эти приложения будут всегда открываться как плавающие окна и не будут
# участвовать в тайлинге. Это поможет избежать их "потери" за экраном.
[[on-window-detected]]
if.app-name-regex-substring = 'telegram|finder|amneziavpn|deep|dicord|mail|quicktime|keepass|skype'
run = 'layout floating'

# Добавляем DockDoor в правила плавающих окон.
# Убедитесь, что 'dockdoor' - это правильное имя процесса/приложения,
# если не сработает, попробуйте 'DockDoor' или найдите точное имя через `aerospace list-windows`
[[on-window-detected]]
if.app-name-regex-substring = 'dockdoor'
run = 'layout floating'

# Ghostty: всегда перемещать на рабочий стол 'T' И делать его окна плавающими.
# Это решает проблему "вкладок" Ghostty.
[[on-window-detected]]
if.app-name-regex-substring = 'Ghostty'
run = ['layout floating', 'move-node-to-workspace T']

# Zed: всегда перемещать на рабочий стол 'Z'. По умолчанию будет ТАЙЛИТЬСЯ.
[[on-window-detected]]
if.app-name-regex-substring = 'Zed'
run = 'move-node-to-workspace Z'

# Obsidian: всегда перемещать на рабочий стол 'O'. По умолчанию будет ТАЙЛИТЬСЯ.
[[on-window-detected]]
if.app-name-regex-substring = 'Obsidian'
run = 'move-node-to-workspace O'

[[on-window-detected]]
if.app-name-regex-substring = 'Safari'
run = 'move-node-to-workspace W'


[[on-window-detected]]
if.window-title-regex-substring = 'Preferences|Settings' # или другое точное название окна настроек
run = 'layout floating'


#
# Настройки раскладки клавиатуры
#
[key-mapping]
preset = 'qwerty'

#
# Отступы (gaps) между окнами и краями монитора
#
[gaps]
inner.horizontal = 20 # Горизонтальный отступ между окнами
inner.vertical = 20   # Вертикальный отступ между окнами
outer.left = 20       # Отступ от левого края монитора
outer.bottom = 20     # Отступ от нижнего края монитора
outer.top = 10        # Отступ от верхнего края монитора (уменьшен для заголовков окон)
outer.right = 20      # Отступ от правого края монитора


#
# Горячие клавиши (режим 'main')
#
[mode.main.binding]
# --- Переключение между плавающим и тайловым/полноэкранным режимами ---
# Переключение текущего окна в/из полноэкранного режима (без зазоров)
alt-f = 'fullscreen'
# alt-ctrl-shift-f = 'fullscreen'
# Переключение текущего окна между плавающим и тайловым режимами
alt-ctrl-f = 'layout floating tiling'
# Переключение между тайловым режимом и режимом аккордеона
alt-slash = 'layout tiles accordion' # alt + /

# Фокусировка на окнах (влево/вниз/вверх/вправо)
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Переключение между рабочими столами (влево/вправо)
alt-left = 'workspace prev'  # Переключиться на предыдущий рабочий стол
alt-right = 'workspace next' # Переключиться на следующий рабочий стол

# Перемещение окон между тайлами
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Изменение размера окон
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Переключение на рабочий стол (Workspace) по номеру
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'

# Перемещение текущего окна на другой рабочий стол (Workspace)
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'

# --- Решение проблемы с alt-shift-tab ---
# Было: alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
# Теперь: Новая горячая клавиша для перемещения рабочего стола на следующий монитор
# Использование 'alt-ctrl-tab' менее вероятно вызовет конфликт с другими приложениями
alt-ctrl-m = 'move-workspace-to-monitor --wrap-around next'

# Пример для терминала (если Ghostty не используется или нужен другой)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#   do script
#   activate
# end tell'
# '''


# Автоматический запуск и перемещение на нужный рабочий стол
# Если приложение уже запущено, AeroSpace просто сфокусируется на его окне.
# Если рабочего стола нет, AeroSpace его создаст.
alt-t = 'exec-and-forget open -a "Ghostty"; workspace T'
alt-z = 'exec-and-forget open -a "Zed"; workspace Z'
alt-o = 'exec-and-forget open -a "Obsidian"; workspace O'
alt-w = 'exec-and-forget open -a "Safari"; workspace W'
